
development:
 adapter: postgresql
 database: gindb
 pool: 5
 timeout: 5000


production:
 adapter: postgresql
 encoding: utf8
 database: postgres
 username: postgres
 password: scTSW951?~
 host: 35.197.242.201
 port: 5432
