# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
 adapter: postgresql
 database: gindb
 pool: 5
 timeout: 5000


production:
 adapter: pg
 encoding: utf8
 database: <%= ENV['RDS_DB_NAME'] %>
 username: <%= ENV['RDS_USERNAME'] %>
 password: <%= ENV['RDS_PASSWORD'] %>
 host: <%= ENV['RDS_HOSTNAME'] %>
 port: <%= ENV['RDS_PORT'] %>
