
development:
 adapter: postgresql
 database: gindb
 pool: 5
 timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: "postgres"
  password: "scTSW951?~"
  database: "gin-db"
  host:   "/cloudsql/gindetective-193712:europe-west2:gin-db"
